language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "3.4"
      env: DJANGO=1.4
    - python: "3.3"
      env: DJANGO=1.4
    - python: "3.4"
      env: DJANGO=1.3
    - python: "3.3"
      env: DJANGO=1.3
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install pyflakes
before_script:
  - "pep8 --ignore=E128,E501 templated_email"
  - "pyflakes templated_email"
script:
  - python manage.py test
